
local anim = require 'main.modules.animateCalls'

function init(self)
	msg.post(".", "acquire_input_focus")

	anim.animateButton1(gui.get_node("selectMainMenu"), 0.4)
end

function on_input(self, action_id, action)

	-- Process Touching of the Main Menu Button
	if action.released and gui.pick_node(gui.get_node("selectMainMenu"), action.x, action.y) then
		msg.post("main:/main#main", "start_main_menu") 
	end	

end